e2e deployment. assets are placeholders

diff --git a/templates/application.template b/templates/application.template
--- a/templates/application.template
+++ b/templates/application.template
@@ -84,6 +84,8 @@ Parameters:
     AllowedPattern: '[a-zA-Z0-9!^*\-_+]*'
     ConstraintDescription: Can only contain alphanumeric characters or the following
       special characters !^*-_+, between 8 and 28 characters
+  KeyPairName:
+    Type: String
   LogBucket:
     Type: String
     Description: Bucket to write logs to
@@ -149,7 +151,7 @@ Mappings:
       HealthCheckGracePeriod: 300
   Database:
     Defaults:
-      User: hitrust-example-db-user
+      User: HitrustExampleDbUser
   AWSAMIRegionMap:
     AMI:
       AMZNLINUX2HVM: amzn2-ami-hvm-2.0.20190618-x86_64-gp2 
@@ -241,7 +243,6 @@ Resources:
       Tags:
         - Key: !Ref QSTagKey
           Value: !Ref QSTagValue
-    
 
   AppInstanceSecurityGroup:
     Type: AWS::EC2::SecurityGroup
@@ -273,77 +274,79 @@ Resources:
         DBMasterUser: !FindInMap [ Database, Defaults, User]
         DBPassword: !Ref DBPassword
         DBPrivateSubnets: !Join [ "," , !Ref PrivateSubnetDBIds ]
+        QSTagKey: !Ref QSTagKey
+        QSTagValue: !Ref QSTagValue
         SecurityGroupAppInstance: !Ref AppInstanceSecurityGroup
         VpcId: !Ref VpcId
       Tags:
       - Key: !Ref QSTagKey
         Value: !Ref QSTagValue
 
-  WebContentBucket:
-    Type: AWS::S3::Bucket
-    Properties:
-      AccessControl: Private
-      BucketEncryption: 
-        ServerSideEncryptionConfiguration:
-        - ServerSideEncryptionByDefault:
-            SSEAlgorithm: AES256
-      LifecycleConfiguration:
-        Rules:
-        - Id: Transition90days
-          Status: Enabled
-          Transition:
-            TransitionInDays: 90
-            StorageClass: !FindInMap [ Storage, Defaults, ArchiveTier ]
-      LoggingConfiguration:
-        DestinationBucketName: !Ref LogBucket
-        LogFilePrefix: !FindInMap [ Storage, WebContent, LogPrefix ]
-      Tags:
-      - Key: !Ref QSTagKey
-        Value: !Ref QSTagValue
-      VersioningConfiguration:
-        Status: Enabled
-  WebContentS3Policy:
-    Type: AWS::S3::BucketPolicy
-    DependsOn: WebContentBucket
-    Properties:
-      Bucket: !Ref WebContentBucket
-      PolicyDocument:
-        Statement:
-        - Sid: EnforceSecureTransport
-          Action: s3:*
-          Effect: Deny
-          Principal: '*'
-          Resource:
-            !Sub
-            - arn:${Partition}:s3:::${WebContentBucket}
-            - Partition: !If [ GovCloudCondition, aws-us-gov, aws ]
-          Condition:
-            Bool:
-              aws:SecureTransport: 'false'
-        - Sid: EnforceEncryptionOnPut
-          Effect: Deny
-          Principal: '*'
-          Action: s3:PutObject
-          Resource:
-            !Sub
-            - arn:${Partition}:s3:::${WebContentBucket}/*
-            - Partition: !If [ GovCloudCondition, aws-us-gov, aws ]
-          Condition:
-            StringNotEquals:
-              s3:x-amz-server-side-encryption: AES256
-  CleanupWebBucket:
-    Type: AWS::CloudFormation::Stack
-    DependsOn:
-    - WebContentBucket
-    Properties:
-      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/clean-bucket.template
-      Parameters:
-        Bucket: !Ref WebContentBucket
-        QSTagKey: !Ref QSTagKey
-        QSTagValue: !Ref QSTagValue
-      Tags:
-      - Key: !Ref QSTagKey
-        Value: !Ref QSTagValue
+#  WebContentBucket:
+#    Type: AWS::S3::Bucket
+#    Properties:
+#      AccessControl: Private
+#      BucketEncryption: 
+#        ServerSideEncryptionConfiguration:
+#        - ServerSideEncryptionByDefault:
+#            SSEAlgorithm: AES256
+#      LifecycleConfiguration:
+#        Rules:
+#        - Id: Transition90days
+#          Status: Enabled
+#          Transition:
+#            TransitionInDays: 90
+#            StorageClass: !FindInMap [ Storage, Defaults, ArchiveTier ]
+#      LoggingConfiguration:
+#        DestinationBucketName: !Ref LogBucket
+#        LogFilePrefix: !FindInMap [ Storage, WebContent, LogPrefix ]
+#      Tags:
+#      - Key: !Ref QSTagKey
+#        Value: !Ref QSTagValue
+#      VersioningConfiguration:
+#        Status: Enabled
+#  WebContentS3Policy:
+#    Type: AWS::S3::BucketPolicy
+#    DependsOn: WebContentBucket
+#    Properties:
+#      Bucket: !Ref WebContentBucket
+#      PolicyDocument:
+#       Statement:
+#        - Sid: EnforceSecureTransport
+#          Action: s3:*
+#          Effect: Deny
+#          Principal: '*'
+#          Resource:
+#            !Sub
+#            - arn:${Partition}:s3:::${WebContentBucket}
+#            - Partition: !If [ GovCloudCondition, aws-us-gov, aws ]
+#          Condition:
+#            Bool:
+#              aws:SecureTransport: 'false'
+#        - Sid: EnforceEncryptionOnPut
+#          Effect: Deny
+#          Principal: '*'
+#          Action: s3:PutObject
+#          Resource:
+#            !Sub
+#            - arn:${Partition}:s3:::${WebContentBucket}/*
+#            - Partition: !If [ GovCloudCondition, aws-us-gov, aws ]
+#          Condition:
+#            StringNotEquals:
+#              s3:x-amz-server-side-encryption: AES256
+#  CleanupWebBucket:
+#    Type: AWS::CloudFormation::Stack
+#    DependsOn:
+#    - WebContentBucket
+#    Properties:
+#      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/clean-bucket.template
+#      Parameters:
+#        Bucket: !Ref WebContentBucket
+#        QSTagKey: !Ref QSTagKey
+#        QSTagValue: !Ref QSTagValue
+#      Tags:
+#      - Key: !Ref QSTagKey
+#        Value: !Ref QSTagValue
 
   AppInstanceRole:
     Type: AWS::IAM::Role
@@ -368,6 +371,16 @@ Resources:
             - ec2:Describe*
             - ec2:CreateTags
             Resource: "*"
+      - PolicyName: GetObj
+        PolicyDocument:
+          Version: 2012-10-17
+          Statement:
+          - Effect: Allow
+            Action:
+            - s3:GetObject
+            Resource: !Sub
+            - arn:${Partition}:s3:::${QSS3BucketName}/${QSS3KeyPrefix}*
+            - Partition: !If [ GovCloudCondition, aws-us-gov, aws ]
   AppInstanceProfile:
     Type: AWS::IAM::InstanceProfile
     Properties:
@@ -399,8 +412,8 @@ Resources:
               content: !Sub |
                 [cfn-auto-reloader-hook]
                 triggers=post.update
-                path=Resources.rAutoScalingConfigApp.Metadata.AWS::CloudFormation::Init
-                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource AppASG --configsets wordpress_install --region ${AWS::Region}
+                path=Resources.AppLaunchConfig.Metadata.AWS::CloudFormation::Init
+                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource AppLaunchConfig --configsets wordpress_install --region ${AWS::Region}
               mode: '000400'
               owner: root
               group: root
@@ -417,7 +430,7 @@ Resources:
             yum:
               php: []
               php-mysql: []
-              mysql: []
+              mariadb: []
               httpd: []
           sources:
             /var/www/html: https://wordpress.org/latest.tar.gz
@@ -469,17 +482,13 @@ Resources:
       IamInstanceProfile: !Ref AppInstanceProfile
       #InstanceType: !FindInMap [ EC2, !Ref "AWS::Region", InstanceType ]
       InstanceType: m4.large
+      KeyName: !Ref KeyPairName
       BlockDeviceMappings:
       - DeviceName: /dev/xvda
         Ebs:
           VolumeSize: 50
           VolumeType: gp2
           Encrypted: true
-#      - DeviceName: /dev/sdh
-#        Ebs: 
-#          VolumeSize: 50
-#          VolumeType: gp2
-#          Encrypted: true
       SecurityGroups:
       - !Ref AppInstanceSecurityGroup
       UserData:
@@ -491,48 +500,43 @@ Resources:
 
             yum update -y && yum install -y mod_ssl
 
+            echo aws configure set default.s3.signature_version s3v4 >> /home/ec2-user/tmp.log
             aws configure set default.s3.signature_version s3v4
-            aws configure set region ${AWS::Region}
-
+            echo aws configure set region ${AWS::Region} >> /home/ec2-user/tmp.log
+            aws configure set region ${AWS::Region} 
             # Tag volumes
-            EC2_INSTANCE_ID=$(curl -s http://instance-data/latest/meta-data/instance-id)
+            echo "Tagging volumes" >> /home/ec2-user/tmp.log
+
+            echo EC2_INSTANCE_ID=$(curl -s http://instance-data/latest/meta-data/instance-id) >> /home/ec2-user/tmp.log
+            EC2_INSTANCE_ID=$(curl -s http://instance-data/latest/meta-data/instance-id) 
+
+            echo DISK_IDS=$(aws ec2 describe-volumes --filters Name=attachment.instance-id,Values=$EC2_INSTANCE_ID --query 'Volumes[*].[VolumeId]' --region=${AWS::Region} --out "text" | cut -f 1) >> /home/ec2-user/tmp.log
             DISK_IDS=$(aws ec2 describe-volumes --filters Name=attachment.instance-id,Values=$EC2_INSTANCE_ID --query 'Volumes[*].[VolumeId]' --region=${AWS::Region} --out "text" | cut -f 1)
+
+            echo aws ec2 create-tags --resources $DISK_IDS --tags Key=${QSTagKey},Value=${QSTagValue} --region ${AWS::Region} >> /home/ec2-user/tmp.log
             aws ec2 create-tags --resources $DISK_IDS --tags Key=${QSTagKey},Value=${QSTagValue} --region ${AWS::Region}
 
             # Create SSL cert
-            echo Generating self-signed certificate
+            echo "Generating self-signed certificate" >> /home/ec2-user/tmp.log
+
+            # Create and sign certificate
+            if [ -d "/etc/ssl/private" ]
+            then
+              echo "/etc/ssl/private already exists" >> /home/ec2-user/tmp.log
+            else
+              echo "Creating /etc/ssl/private directory" >> /home/ec2-user/tmp.log
+              mkdir /etc/ssl/private
+            fi
+
+            echo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/common.key -out /etc/ssl/certs/common.crt -subj "/C=US/ST=Washington/L=Seattle/O=NonProductionTestCert/CN=NonProductionTestCert" >> /home/ec2-user/tmp.log
             openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/common.key -out /etc/ssl/certs/common.crt -subj "/C=US/ST=Washington/L=Seattle/O=NonProductionTestCert/CN=NonProductionTestCert"
+            
+            echo /opt/aws/bin/cfn-init -v --stack '${AWS::StackName}' --resource AppLaunchConfig --configsets wordpress_install --region '${AWS::Region}' >> /home/ec2-user/tmp.log
+            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource AppLaunchConfig --configsets wordpress_install --region ${AWS::Region}
 
-            ######################################################################
-            # Volume /dev/sdh (which will get created as /dev/xvdh on Amazon Linux)
-
-            #DATA_STATE="unknown"
-            #until [ "${!DATA_STATE}" == "attached" ]; do
-            #  DATA_STATE=$(aws ec2 describe-volumes \
-            #  --region ${AWS::Region} \
-            #  --filters \
-            #        Name=attachment.instance-id,Values=${!EC2_INSTANCE_ID} \
-            #        Name=attachment.device,Values=/dev/sdh \
-            #  --query Volumes[].Attachments[].State \
-            #  --output text)
-
-            #  sleep 5
-            #done
-
-            # Format /dev/xvdh if it does not contain a partition yet
-            #if [ "$(file -b -s /dev/xvdh)" == "data" ]; then
-            #  mkfs -t ext4 /dev/xvdh
-            #fi
-
-            #mkdir -p /data
-            #mount /dev/xvdh /data
-
-            # Persist the volume in /etc/fstab so it gets mounted again
-            #echo '/dev/xvdh /data ext4 defaults,nofail 0 2' >> /etc/fstab
-
-            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource AppASG --configsets wordpress_install --region ${AWS::Region}
-
+            echo cp /tmp/httpd/ssl.conf /etc/httpd/conf.d/ssl.conf >> /home/ec2-user/tmp.log
             cp /tmp/httpd/ssl.conf /etc/httpd/conf.d/ssl.conf
+            echo service httpd restart >> /home/ec2-user/tmp.log
             service httpd restart
 
             ######################################################################
@@ -545,21 +549,24 @@ Resources:
             ######################################################################
 
             # Download the landing page.
-            sudo wget https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}assets/landing/landing.html -O $LANDING_PAGE
+            echo aws s3 cp s3://${QSS3BucketName}/${QSS3KeyPrefix}assets/landing/landing.html $LANDING_PAGE >> /home/ec2-user/tmp.log
+            aws s3 cp s3://${QSS3BucketName}/${QSS3KeyPrefix}assets/landing/landing.html $LANDING_PAGE
 
             # Replace relative image links with links to the production S3 source.
-            sudo sed -i 's|images|https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}assets/landing/images|g' $LANDING_PAGE
-
+            echo sed -i 's|images|https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}assets/landing/images|g' $LANDING_PAGE >> /home/ec2-user/tmp.log
+            sed -i 's|images|https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}assets/landing/images|g' $LANDING_PAGE
             # Inject the landing page branding label.
-            sudo sed -i "s|{compliance-body}|$COMPLIANCE_BODY_LABEL|g" $LANDING_PAGE
-
+            echo sed -i "s|{compliance-body}|$COMPLIANCE_BODY_LABEL|g" $LANDING_PAGE >> /home/ec2-user/tmp.log
+            sed -i "s|{compliance-body}|$COMPLIANCE_BODY_LABEL|g" $LANDING_PAGE
             # Inject the survey link parameter.
-            sudo sed -i "s|{compliance-body-survey-link}|$COMPLIANCE_SURVEY_LINK|g" $LANDING_PAGE
-
-            # Inject the security control matrix file location.
-            sudo sed -i "s|{compliance-body-matrix}|https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}assets/$COMPLIANCE_MATRIX_FILENAME|g" $LANDING_PAGE
-
+            echo sed -i "s|{compliance-body-survey-link}|$COMPLIANCE_SURVEY_LINK|g" $LANDING_PAGE >> /home/ec2-user/tmp.log
+            sed -i "s|{compliance-body-survey-link}|$COMPLIANCE_SURVEY_LINK|g" $LANDING_PAGE 
+            # Inject the security control matrix file location. 
+            echo sed -i "s|{compliance-body-matrix}|https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}assets/$COMPLIANCE_MATRIX_FILENAME|g" $LANDING_PAGE >> /home/ec2-user/tmp.log
+            sed -i "s|{compliance-body-matrix}|https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}assets/$COMPLIANCE_MATRIX_FILENAME|g" $LANDING_PAGE 
+            echo /opt/aws/bin/cfn-signal -e $? --stack '${AWS::StackName}' --resource AppASG --region '${AWS::Region}' >> /home/ec2-user/tmp.log
             /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AppASG --region ${AWS::Region}
+            echo "finished" >> /home/ec2-user/tmp.log
           - QSS3Region: !If [ GovCloudEastCondition, s3-us-gov-east-1, !If [ GovCloudWestCondition, s3-us-gov-west-1, s3 ] ]
 
   AppASG:
